name:                adventofcode21
version:             0.1.0.0
github:              "githubuser/adventofcode21"
license:             BSD3
author:              "wjordan"
maintainer:          "wes@wesj.org"
copyright:           "2021 wjordan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Advent of Code 2021 solutions

dependencies:
- base >= 4.7 && < 5
- vector
- containers
- mtl
- sort

library:
  source-dirs: src

executables:
  adventofcode21-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode21

tests:
  adventofcode21-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode21
